--- 
- 
  apt: 
    update_cache: true
  become: true
  name: "update local apt repo."
- 
  apt: 
    upgrade: true
  become: true
  name: "upgrade apt packages"
- 
  apt: 
    autoremove: true
  become: true
  name: "remove stale dependecies"
- 
  apt: 
    pkg: 
      - nodejs
      - npm
  become: true
  name: "install dependencies [nodejs and npm]"
# - 
#   apt: 
#     name: pm2
#     state: present
#     update_cache: true
#   become: true
#   name: "install pm2"
- 
  become: true
  connection: local
  name: "install rsync on the ansible controller"
  package: 
    name: 
      - openssh
      - rsync
    state: present
- 
  file: 
    path: ~/backend_app
    state: directory
  name: "Create Backend App Directory"
- 
  become: true
  copy: 
    dest: /home/ubuntu/backend_app/artifact.tar.gz
    src: ~/project/artifact.tar.gz
  name: "copy the artifacts into the Backend Instance"
- 
  become: true
  environment: 
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
    TYPEORM_ENTITIES: ./modules/domain/**/*.entity.js
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_MIGRATIONS: ./migrations/*.js
    TYPEORM_MIGRATIONS_DIR: ./migrations
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
  name: "run server"
  shell: |
      cd /home/ubuntu/backend_app
      tar xzvf artifact.tar.gz
      npm install
      npm run build
      pm2 stop all
      pm2 start npm -- start
