---
  - name: "update local apt repo."
    become: true
    apt:
      update_cache: yes
  
  - name: "upgrade apt packages"
    become: true
    apt:
      upgrade: yes

  - name: "remove stale dependecies"
    become: true
    apt:
      autoremove: yes

  - name: "install dependencies [nodejs and npm]"
    become: true
    apt:
      name:["nodejs","npm"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: true
    apt:
      name:pm2
      global: yes
      production: yes
      state: present
      update_cache: yes
    
  - name: install rsync on the ansible controller
    become: yes
    connection: local
    package:
      name: 
        - openssh
        - rsync
      state: present
      
  - name: "Create Backend App Directory"
    file:
      path: ~/backend_app
      state: directory

  - name: "copy the artifacts into the Backend Instance"
    become: yes
    copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/backend_app/artifact.tar.gz

  - name: "run server"
    become: true
    shell: |
      cd /home/ubuntu/backend_app
      tar xzvf artifact.tar.gz
      npm install
      npm run build
      pm2 stop all
      pm2 start npm -- start
    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
